/**
 * EMPIRE AI V49 — PM2 Ecosystem Config
 * ======================================
 * Manages all PM2-managed services with proper restart limits,
 * graceful shutdown timeouts, and memory limits to prevent
 * crash loops and port conflicts.
 *
 * Apply changes:
 *   pm2 delete ecosystem.config.js   # remove old instance
 *   pm2 start ecosystem.config.js     # start with new config
 *
 * Or hot-reload individual processes:
 *   pm2 restart empire-hub
 *   pm2 restart empire-mesh
 */

module.exports = {
  apps: [
    // ── Empire Hub (FastAPI, port 8000) ──────────────────────────
    {
      name: 'empire-hub',
      script: '/root/empire-v49/hub.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
      },

      // ── Port conflict prevention ──────────────────────────────
      // Time (ms) to wait for the app to start listening.
      // If it doesn't bind within this window, PM2 marks it failed.
      listen_timeout: 30000,

      // ── Graceful shutdown ─────────────────────────────────────
      // After SIGTERM, wait this long before SIGKILL. The hub needs
      // time to close DB connections, finish in-flight requests, etc.
      kill_timeout: 10000,

      // ── Crash-loop prevention ─────────────────────────────────
      // Max consecutive restarts within min_uptime window.
      // After this, PM2 stops trying (status: errored).
      max_restarts: 10,

      // Min uptime (ms) for a restart to count as "successful."
      // If the process crashes faster than this, it's counted toward
      // max_restarts exponentially (PM2's backoff).
      min_uptime: 20000,

      // Delay (ms) between restart attempts (after min_uptime check).
      restart_delay: 2000,

      // Auto-restart if memory exceeds this limit.
      max_memory_restart: '600M',

      // ── Logging ───────────────────────────────────────────────
      error_file: '/root/.pm2/logs/empire-hub-error.log',
      out_file: '/root/.pm2/logs/empire-hub-out.log',
      pid_file: '/root/.pm2/pids/empire-hub.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Empire Mesh (background orchestrator) ───────────────────
    {
      name: 'empire-mesh',
      script: '/root/empire-v49/main.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      listen_timeout: 15000,
      kill_timeout: 8000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/empire-mesh-error.log',
      out_file: '/root/.pm2/logs/empire-mesh-out.log',
      pid_file: '/root/.pm2/pids/empire-mesh.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    // ── Hermes Dashboard (port 9119) ───────────────────────────
    {
      name: 'hermes-dashboard',
      script: '/usr/local/bin/hermes',
      args: 'dashboard --port 9119',
      cwd: '/root/.hermes',
      exec_mode: 'fork',
      instances: 1,
      env: {
        HERMES_HOME: '/root/.hermes',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/hermes-dashboard-error.log',
      out_file: '/root/.pm2/logs/hermes-dashboard-out.log',
      pid_file: '/root/.pm2/pids/hermes-dashboard.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Synthetic Brain (LLM, port 8005) via uvicorn ────────────────
    {
      name: 'synthetic-brain',
      script: '/usr/local/bin/uvicorn',
      args: 'synthetic_brain:app --host 0.0.0.0 --port 8005',
      cwd: '/root/empire-v49',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 20000,
      kill_timeout: 15000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '2G',
      error_file: '/root/.pm2/logs/synthetic-brain-error.log',
      out_file: '/root/.pm2/logs/synthetic-brain-out.log',
      pid_file: '/root/.pm2/pids/synthetic-brain.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Agent Orchestrator (port 8042) via uvicorn ─────────────────────
    {
      name: 'agent-orchestrator',
      script: '/usr/local/bin/uvicorn',
      args: 'agent_orchestrator:app --host 0.0.0.0 --port 8042',
      cwd: '/root/empire-v49',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/agent-orchestrator-error.log',
      out_file: '/root/.pm2/logs/agent-orchestrator-out.log',
      pid_file: '/root/.pm2/pids/agent-orchestrator.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Hook Analytics (port 8046) ─────────────────────────────────────
    {
      name: 'hook-analytics',
      script: '/root/empire-v49/hook_analytics.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/hook-analytics-error.log',
      out_file: '/root/.pm2/logs/hook-analytics-out.log',
      pid_file: '/root/.pm2/pids/hook-analytics.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Error Watcher (agent error monitoring → watcher_findings table) ──
    {
      name: 'error-watcher',
      script: '/root/empire-v49/bots/error_watcher.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--interval 300',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/error-watcher-error.log',
      out_file: '/root/.pm2/logs/error-watcher-out.log',
      pid_file: '/root/.pm2/pids/error-watcher.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Space Reasoner (deep reasoning: Gemini → Claude → Ollama) ──────
    {
      name: 'space-reasoner',
      script: '/root/empire-v49/bots/space_reasoner.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/space-reasoner-error.log',
      out_file: '/root/.pm2/logs/space-reasoner-out.log',
      pid_file: '/root/.pm2/pids/space-reasoner.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Autonomous Supervisor (loop agent + PM2 health) ────────────────
    {
      name: 'autonomous-supervisor',
      script: '/root/empire-v49/empire_autonomous_supervisor.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/autonomous-supervisor-error.log',
      out_file: '/root/.pm2/logs/autonomous-supervisor-out.log',
      pid_file: '/root/.pm2/pids/autonomous-supervisor.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Affiliate Recruiter (auto-recruit + nurture affiliates) ────────
    {
      name: 'affiliate-recruiter',
      script: '/root/empire-v49/bots/affiliate_recruiter.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        AFFILIATE_RECRUITER_INTERVAL: '60',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/affiliate-recruiter-error.log',
      out_file: '/root/.pm2/logs/affiliate-recruiter-out.log',
      pid_file: '/root/.pm2/pids/affiliate-recruiter.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── SEO Agent (AI-powered SEO optimization loop) ───────────────────
    {
      name: 'seo-agent',
      script: '/root/empire-v49/bots/seo_agent.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        SEO_INTERVAL_HOURS: '6',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/seo-agent-error.log',
      out_file: '/root/.pm2/logs/seo-agent-out.log',
      pid_file: '/root/.pm2/pids/seo-agent.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Email Pulse Monitor (dispatch queue + tracking observer) ────────
    {
      name: 'email-pulse-monitor',
      script: '/root/empire-v49/bots/email_pulse_monitor.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        EMAIL_PULSE_INTERVAL_MINUTES: '15',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/email-pulse-monitor-error.log',
      out_file: '/root/.pm2/logs/email-pulse-monitor-out.log',
      pid_file: '/root/.pm2/pids/email-pulse-monitor.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Traffic Specialist (cross-channel traffic orchestration) ────────
    {
      name: 'traffic-specialist',
      script: '/root/empire-v49/bots/traffic_specialist.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        TRAFFIC_SPECIALIST_INTERVAL: '30',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/traffic-specialist-error.log',
      out_file: '/root/.pm2/logs/traffic-specialist-out.log',
      pid_file: '/root/.pm2/pids/traffic-specialist.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Stop Loss Bot (position monitoring + stop loss execution) ───────
    {
      name: 'stop-loss-bot',
      script: '/root/empire-v49/bots/stop_loss_bot.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        STOPLOSS_INTERVAL_SEC: '15',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/stop-loss-bot-error.log',
      out_file: '/root/.pm2/logs/stop-loss-bot-out.log',
      pid_file: '/root/.pm2/pids/stop-loss-bot.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Vault Wallet Monitor (Solana USDC balance → Telegram alert) ───
    {
      name: 'vault-monitor',
      script: '/root/empire-v49/scripts/vault_monitor.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop --interval 60',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/vault-monitor-error.log',
      out_file: '/root/.pm2/logs/vault-monitor-out.log',
      pid_file: '/root/.pm2/pids/vault-monitor.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Daily Revenue Report (fees, claims, ledger → Telegram) ───────
    {
      name: 'daily-revenue',
      script: '/root/empire-v49/agents_daily_revenue.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 10000,
      restart_delay: 5000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/daily-revenue-error.log',
      out_file: '/root/.pm2/logs/daily-revenue-out.log',
      pid_file: '/root/.pm2/pids/daily-revenue.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Agent OS Mission Control (standalone, port 8060) ────────────
    {
      name: 'mc-os',
      script: '/usr/local/bin/uvicorn',
      args: 'empire_mission_control_os:standalone_app --host 0.0.0.0 --port 8060',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 10000,
      restart_delay: 3000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mc-os-error.log',
      out_file: '/root/.pm2/logs/mc-os-out.log',
      pid_file: '/root/.pm2/pids/mc-os.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Marketing Worker (poll agent_task_queue for marketing.* tasks) ──
    {
      name: 'mesh-marketing',
      script: '/root/empire-v49/bots/mesh_marketing_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_MARKETING_POLL_SEC: '30',
      },
      // Polling worker — no HTTP server, short listen_timeout
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-marketing-error.log',
      out_file: '/root/.pm2/logs/mesh-marketing-out.log',
      pid_file: '/root/.pm2/pids/mesh-marketing.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Swarm Worker (swarm.fire + swarm.strike_video via Ollama/Kokoro/FFmpeg) ──
    {
      name: 'mesh-swarm',
      script: '/root/empire-v49/bots/swarm_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        SWARM_WORKER_INTERVAL_HOURS: '6',
        SWARM_MESH_POLL_SEC: '30',
      },
      // Polling worker — no HTTP server, short listen_timeout
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/mesh-swarm-error.log',
      out_file: '/root/.pm2/logs/mesh-swarm-out.log',
      pid_file: '/root/.pm2/pids/mesh-swarm.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Dispatcher (poll agent_task_queue for revenue.connect_buyer tasks) ──
    {
      name: 'mesh-dispatcher',
      script: '/root/empire-v49/bots/mesh_dispatcher.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_DISPATCHER_INTERVAL_SEC: '120',
      },
      // Polling worker — no HTTP server, short listen_timeout
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/mesh-dispatcher-error.log',
      out_file: '/root/.pm2/logs/mesh-dispatcher-out.log',
      pid_file: '/root/.pm2/pids/mesh-dispatcher.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Scout Worker (poll agent_task_queue for scout.find_roofs tasks) ──
    {
      name: 'mesh-scout',
      script: '/root/empire-v49/bots/mesh_scout.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_SCOUT_INTERVAL_SEC: '3600',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-scout-error.log',
      out_file: '/root/.pm2/logs/mesh-scout-out.log',
      pid_file: '/root/.pm2/pids/mesh-scout.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Outreach Worker (poll agent_task_queue for scout.find_roofs tasks → draft emails) ──
    {
      name: 'mesh-outreach',
      script: '/root/empire-v49/bots/mesh_outreach.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_OUTREACH_INTERVAL_SEC: '60',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-outreach-error.log',
      out_file: '/root/.pm2/logs/mesh-outreach-out.log',
      pid_file: '/root/.pm2/pids/mesh-outreach.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Studio Copy Worker (poll for studio.write_script tasks → write reel scripts) ──
    {
      name: 'mesh-studio-copy',
      script: '/root/empire-v49/bots/mesh_studio_copy.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_STUDIO_COPY_INTERVAL_SEC: '1800',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-studio-copy-error.log',
      out_file: '/root/.pm2/logs/mesh-studio-copy-out.log',
      pid_file: '/root/.pm2/pids/mesh-studio-copy.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Studio Render Worker (poll agent_task_queue for studio.render_reel tasks → FFmpeg) ──
    {
      name: 'mesh-studio-render',
      script: '/root/empire-v49/bots/mesh_studio_render.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_STUDIO_RENDER_INTERVAL_SEC: '30',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/mesh-studio-render-error.log',
      out_file: '/root/.pm2/logs/mesh-studio-render-out.log',
      pid_file: '/root/.pm2/pids/mesh-studio-render.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Quality Analyst (score call recordings → call_logs, also handles revenue.score_call) ──
    {
      name: 'mesh-quality',
      script: '/root/empire-v49/bots/quality_analyst.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      args: '--loop',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_QUALITY_POLL_SEC: '300',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/mesh-quality-error.log',
      out_file: '/root/.pm2/logs/mesh-quality-out.log',
      pid_file: '/root/.pm2/pids/mesh-quality.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Scraper Worker (poll agent_task_queue for scrape.web + scrape.crawl tasks) ──
    {
      name: 'mesh-scraper',
      script: '/root/empire-v49/bots/mesh_scraper.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_SCRAPER_POLL_SEC: '60',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-scraper-error.log',
      out_file: '/root/.pm2/logs/mesh-scraper-out.log',
      pid_file: '/root/.pm2/pids/mesh-scraper.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Orchestrator Worker (poll agent_task_queue for agentic.plan + agentic.review tasks) ──
    {
      name: 'mesh-orchestrator',
      script: '/root/empire-v49/bots/mesh_orchestrator_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_ORCHESTRATOR_POLL_SEC: '60',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/mesh-orchestrator-error.log',
      out_file: '/root/.pm2/logs/mesh-orchestrator-out.log',
      pid_file: '/root/.pm2/pids/mesh-orchestrator.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Autoresearch Worker (poll agent_task_queue for autoresearch.run tasks) ──
    {
      name: 'mesh-autoresearch',
      script: '/root/empire-v49/bots/mesh_autoresearch_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_AUTORESEARCH_POLL_SEC: '120',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/mesh-autoresearch-error.log',
      out_file: '/root/.pm2/logs/mesh-autoresearch-out.log',
      pid_file: '/root/.pm2/pids/mesh-autoresearch.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Mesh Sovereign Worker (poll agent_task_queue for sovereign.* AGI tasks) ──
    {
      name: 'mesh-sovereign',
      script: '/root/empire-v49/bots/mesh_sovereign_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        MESH_SOVEREIGN_POLL_SEC: '120',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/mesh-sovereign-error.log',
      out_file: '/root/.pm2/logs/mesh-sovereign-out.log',
      pid_file: '/root/.pm2/pids/mesh-sovereign.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Sovereign AGI Matrix (sovereign intelligence layer, port 8010) ──
    {
      name: 'sovereign-matrix',
      script: '/root/empire-v49/matrix/sovereign_agi_matrix.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        PYTHONPATH: '/root/empire-v49',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/sovereign-matrix-error.log',
      out_file: '/root/.pm2/logs/sovereign-matrix-out.log',
      pid_file: '/root/.pm2/pids/sovereign-matrix.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Omni Bridge (Deepgram STT → Zernio social distribution, port 8040) ──
    {
      name: 'omni-bridge',
      script: '/root/empire-v49/products/omni_bridge.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        OMNI_PORT: '8040',
        OMNI_HOST: '0.0.0.0',
      },
      // FastAPI app — needs time to bind to port
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 20000,
      restart_delay: 3000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/omni-bridge-error.log',
      out_file: '/root/.pm2/logs/omni-bridge-out.log',
      pid_file: '/root/.pm2/pids/omni-bridge.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Omni Cloner (yt-dlp 1000+ sites → ffmpeg → Deepgram → Zernio, port 8041) ──
    {
      name: 'omni-cloner',
      script: '/root/empire-v49/products/omni_cloner.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        OMNI_CLONER_PORT: '8041',
        OMNI_CLONER_HOST: '0.0.0.0',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 20000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/omni-cloner-error.log',
      out_file: '/root/.pm2/logs/omni-cloner-out.log',
      pid_file: '/root/.pm2/pids/omni-cloner.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Omni Studio (video editing + AI avatar generation, port 8043) ──
    {
      name: 'omni-studio',
      script: '/root/empire-v49/products/omni_studio.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        OMNI_STUDIO_PORT: '8043',
        OMNI_STUDIO_HOST: '0.0.0.0',
      },
      listen_timeout: 15000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 20000,
      restart_delay: 3000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/omni-studio-error.log',
      out_file: '/root/.pm2/logs/omni-studio-out.log',
      pid_file: '/root/.pm2/pids/omni-studio.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Buffy Buffer — Queue Controller (concurrency gate for video renders) ──
    {
      name: 'buffy-buffer',
      script: '/root/empire-v49/bots/buffy_buffer.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        BUFFY_MAX_CONCURRENT: '3',
        BUFFY_POLL_SEC: '3',
        BUFFY_STUCK_MINUTES: '15',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '200M',
      error_file: '/root/.pm2/logs/buffy-buffer-error.log',
      out_file: '/root/.pm2/logs/buffy-buffer-out.log',
      pid_file: '/root/.pm2/pids/buffy-buffer.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Buffy Worker — Render Executor (picks up RENDER_TRIGGERED jobs) ──
    {
      name: 'buffy-worker',
      script: '/root/empire-v49/bots/buffy_worker.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        BUFFY_WORKER_POLL_SEC: '30',
        BUFFY_WORKER_HEARTBEAT_SEC: '60',
      },
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/buffy-worker-error.log',
      out_file: '/root/.pm2/logs/buffy-worker-out.log',
      pid_file: '/root/.pm2/pids/buffy-worker.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Empire Facebook Bot (Messenger lead gen, polling mode) ──

    // ── Empire Facebook Bot (Messenger lead gen, polling mode) ──
    {
      name: 'empire-facebook-bot',
      script: '/root/empire-v49/parking_lot/bots/empire_facebook_bot.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: {
        PYTHONUNBUFFERED: '1',
        FB_BOT_INTERVAL_MINUTES: '5',
      },
      // Polling bot — no HTTP server, so skip listen_timeout
      listen_timeout: 3000,
      kill_timeout: 10000,
      max_restarts: 10,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '250M',
      error_file: '/root/.pm2/logs/empire-facebook-bot-error.log',
      out_file: '/root/.pm2/logs/empire-facebook-bot-out.log',
      pid_file: '/root/.pm2/pids/empire-facebook-bot.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

    // ── Empire Matrix Services (per AGENTS.md, were missing from config) ──
    {
      name: 'empire-matrix-agi',
      script: '/root/empire-v49/matrix/sovereign_agi_matrix.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 30000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/empire-matrix-agi-error.log',
      out_file: '/root/.pm2/logs/empire-matrix-agi-out.log',
      pid_file: '/root/.pm2/pids/empire-matrix-agi.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-matrix-strategy',
      script: '/root/empire-v49/strategy/roi_marketing_matrix.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 30000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/empire-matrix-strategy-error.log',
      out_file: '/root/.pm2/logs/empire-matrix-strategy-out.log',
      pid_file: '/root/.pm2/logs/empire-matrix-strategy.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-matrix-landing',
      script: '/root/empire-v49/landing/landing_matrix.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 30000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/empire-matrix-landing-error.log',
      out_file: '/root/.pm2/logs/empire-matrix-landing-out.log',
      pid_file: '/root/.pm2/logs/empire-matrix-landing.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-matrix-universal',
      script: '/root/empire-v49/universal/universal_matrix.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 30000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '500M',
      error_file: '/root/.pm2/logs/empire-matrix-universal-error.log',
      out_file: '/root/.pm2/logs/empire-matrix-universal-out.log',
      pid_file: '/root/.pm2/logs/empire-matrix-universal.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-ppc-inbound',
      script: '/root/empire-v49/matrix/main.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 30000,
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/empire-ppc-inbound-error.log',
      out_file: '/root/.pm2/logs/empire-ppc-inbound-out.log',
      pid_file: '/root/.pm2/logs/empire-ppc-inbound.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-chrome',
      script: '/root/empire-v49/scripts/chrome_headless.sh',
      cwd: '/root/empire-v49',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      env: { CHROME_DEBUG_PORT: '9222', XVFB_DISPLAY: ':99' },
      listen_timeout: 30000,
      kill_timeout: 8000,
      max_restarts: 5,
      min_uptime: 20000,
      restart_delay: 5000,
      max_memory_restart: '800M',
      error_file: '/root/.pm2/logs/empire-chrome-error.log',
      out_file: '/root/.pm2/logs/empire-chrome-out.log',
      pid_file: '/root/.pm2/logs/empire-chrome.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'empire-pulse-cron',
      script: '/root/empire-v49/scripts/pulse_refresh_cron.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      args: '--interval 300',
      env: { PYTHONUNBUFFERED: '1', PULSE_REFRESH_INTERVAL_SEC: '300' },
      listen_timeout: 15000,
      kill_timeout: 8000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/empire-pulse-cron-error.log',
      out_file: '/root/.pm2/logs/empire-pulse-cron-out.log',
      pid_file: '/root/.pm2/logs/empire-pulse-cron.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'contractor-sniper',
      script: '/root/empire-v49/bots/contractor_sniper.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 8000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 3000,
      max_memory_restart: '400M',
      error_file: '/root/.pm2/logs/contractor-sniper-error.log',
      out_file: '/root/.pm2/logs/contractor-sniper-out.log',
      pid_file: '/root/.pm2/logs/contractor-sniper.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'self-healer',
      script: '/root/empire-v49/agents/self_healer.py',
      cwd: '/root/empire-v49',
      interpreter: 'python3',
      exec_mode: 'fork',
      instances: 1,
      args: '--loop --interval 300',
      env: { PYTHONUNBUFFERED: '1' },
      listen_timeout: 15000,
      kill_timeout: 8000,
      max_restarts: 5,
      min_uptime: 15000,
      restart_delay: 5000,
      max_memory_restart: '300M',
      error_file: '/root/.pm2/logs/self-healer-error.log',
      out_file: '/root/.pm2/logs/self-healer-out.log',
      pid_file: '/root/.pm2/logs/self-healer.pid',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },

  ],
};
