#!/bin/bash
# ══════════════════════════════════════════════════════════════════════
# EMPIRE HUB SAFE RESTART
# ══════════════════════════════════════════════════════════════════════
# Validates all imports before restarting empire-hub.
# If validation fails, does NOT restart — prints what's broken.
#
# Usage:
#   ./hub_safe_restart.sh              # validate + restart
#   ./hub_safe_restart.sh --force       # restart even if validation warns
#   ./hub_safe_restart.sh --validate    # only validate, don't restart
#   ./hub_safe_restart.sh --quick       # fast check (hub.py only)
#   ./hub_safe_restart.sh --status      # show hub status + last crash
# ══════════════════════════════════════════════════════════════════════

set -euo pipefail

cd /root/empire-v49
SCRIPT_DIR=$(dirname "$0")
FORCE=false
VALIDATE_ONLY=false
QUICK=false
STATUS_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    --validate) VALIDATE_ONLY=true ;;
    --quick) QUICK=true ;;
    --status) STATUS_ONLY=true ;;
    --help)
      echo "Empire Hub Safe Restart"
      echo "  ./hub_safe_restart.sh              — validate + restart"
      echo "  ./hub_safe_restart.sh --force       — restart anyway"
      echo "  ./hub_safe_restart.sh --validate    — only validate"
      echo "  ./hub_safe_restart.sh --quick       — fast check (hub.py only)"
      echo "  ./hub_safe_restart.sh --status      — show hub status"
      exit 0 ;;
  esac
done

# ── Status mode: just show hub status ───────────────────────────────
if [ "$STATUS_ONLY" = true ]; then
  echo "─── Hub Status ───"
  pm2 show empire-hub 2>/dev/null | grep -E 'status|restarts|uptime|name' || echo "empire-hub not found in PM2"
  echo ""
  echo "─── Last 10 crash lines ───"
  pm2 logs empire-hub --lines 15 --nostream 2>/dev/null | tail -10 || echo "(no logs)"
  exit 0
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║     EMPIRE HUB SAFE RESTART                              ║"
echo "║     Validates → Restarts → Verifies                     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Run validation ─────────────────────────────────────────
VALIDATE_CMD="$SCRIPT_DIR/validate_hub_deploy.sh"
if [ "$QUICK" = true ]; then
  VALIDATE_CMD="$VALIDATE_CMD --quick"
fi

echo "─── [1/3] Validating deployment ───"
echo ""

if ! $VALIDATE_CMD; then
  echo ""
  if [ "$FORCE" = true ]; then
    echo "  ⚠️  Force flag set — restarting despite validation failures"
  else
    echo "  ❌  Validation FAILED — hub NOT restarted"
    echo "  Fix the errors above, then re-run: $0"
    echo ""
    echo "  To restart anyway: $0 --force"
    echo "  To validate only:  $0 --validate"
    echo "  For quick check:   $0 --quick"
    exit 1
  fi
fi

if [ "$VALIDATE_ONLY" = true ]; then
  echo ""
  echo "  ✅  Validation complete — hub not restarted (--validate mode)"
  exit 0
fi

# ── Step 2: Restart hub ─────────────────────────────────────────────
echo ""
echo "─── [2/3] Restarting empire-hub ───"
# Try restart first; if PM2 doesn't have the process, start it
pm2 restart empire-hub 2>&1 || pm2 start hub.py --name empire-hub 2>&1 || {
  echo "  ❌  Failed to start empire-hub"
  echo "  Try: pm2 start hub.py --name empire-hub"
  exit 1
}

# ── Pre-commit hook setup (first run only) ──────────────────────────
if [ ! -f .git/hooks/pre-commit ]; then
  mkdir -p .git/hooks 2>/dev/null
  cat > .git/hooks/pre-commit << 'HOOK'
#!/bin/bash
# Auto-generated by hub_safe_restart.sh
# Runs validation before every commit to prevent broken code from deploying.
cd "$(git rev-parse --show-toplevel)"
exec ./validate_hub_deploy.sh --quick
HOOK
  chmod +x .git/hooks/pre-commit
  echo "  🔗  Pre-commit hook installed — validation runs before every git commit"
fi

# ── Step 3: Verify hub comes up ─────────────────────────────────────
echo ""
echo "─── [3/3] Verifying hub startup ───"

# Wait for hub to start (up to 15 seconds)
for i in $(seq 1 15); do
  sleep 1
  if curl -s --max-time 2 http://localhost:8000/ >/dev/null 2>&1; then
    echo "  ✅  Hub is responding on port 8000 (${i}s)"
    break
  fi
  if [ "$i" -eq 15 ]; then
    echo "  ⚠️  Hub not responding after 15s — checking logs..."
    echo ""
    pm2 logs empire-hub --lines 20 --nostream 2>/dev/null | tail -20
    echo ""
    echo "  Try: pm2 logs empire-hub --lines 50 --nostream"
    echo "  Or:  $0 --status"
    exit 1
  fi
done

# Show final status
echo ""
pm2 show empire-hub 2>/dev/null | grep -E 'status|restarts|uptime' | sed 's/^/  /'
echo ""
echo "  ✅  Hub restarted successfully"
echo "  Logs: pm2 logs empire-hub --lines 20 --nostream"
echo ""
