-- =============================================================================
-- EMPIRE V49 · DDL MIGRATION 046: CRYPTO PAYMENT REQUESTS
-- =============================================================================
-- Tracks USDC payment requests for product subscriptions. When a user wants
-- to subscribe via crypto, a payment request is created with the exact USDC
-- amount. The Helius webhook matches incoming vault payments to these requests
-- by memo (EMP-XXXXXX), falling back to sender+amount for backward compat.
--
-- Flow:
--   1. POST /api/v1/crypto/pay  → creates a payment request (status: pending)
--   2. User sends exact USDC amount + memo to vault wallet from their wallet
--   3. Helius webhook fires → matches by memo (or sender+amount fallback)
--   4. Payment request transitions: pending → activation_pending → completed
--      (or activation_failed if subscription activation fails)
--
-- STATE MACHINE
--   pending ──(payment detected)──→ activation_pending ──(success)──→ completed
--                                                       ──(failure)──→ activation_failed
--
-- Idempotent: IF NOT EXISTS. Safe to re-run.
-- =============================================================================


CREATE TABLE IF NOT EXISTS public.crypto_payment_requests (
    id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),

    -- Who's buying
    customer_email              text NOT NULL,
    customer_account_id         text NOT NULL,

    -- What they're buying (from product_metadata)
    product_slug                text NOT NULL,
    tier_level                  text NOT NULL,
    amount_usdc                 numeric(12,2) NOT NULL CHECK (amount_usdc > 0),

    -- Payment tracking
    status                      text NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending', 'partial', 'activation_pending', 'completed', 'expired', 'activation_failed', 'failed')),

    transaction_signature       text,          -- filled by webhook when payment arrives
    sender_address              text,          -- user's wallet that sent USDC
    paid_at                     timestamptz,   -- when payment was detected
    paid_amount_usdc            numeric(12,2), -- actual amount received (may differ slightly)
    memo                        text,          -- EMP-XXXXXX generated by engine; user must include in tx

    -- Who created this (operator ID or 'self-serve')
    created_by                  text DEFAULT 'self-serve',

    -- Expiry
    expires_at                  timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),

    -- Notes
    notes                       text DEFAULT ''
);

COMMENT ON TABLE public.crypto_payment_requests IS 'USDC payment requests for self-hosted crypto checkout. Matched by Helius webhook.';


-- ── ALTER EXISTING TABLE (idempotent if table was created by earlier migration) ──
-- Update the CHECK constraint to include activation_pending and activation_failed.
DO $$
BEGIN
    -- Drop the old constraint if it still has the narrower set of values.
    -- The original constraint was:
    --   CHECK (status IN ('pending', 'partial', 'completed', 'expired', 'failed'))
    -- We replace it with the wider set.
    ALTER TABLE public.crypto_payment_requests
        DROP CONSTRAINT IF EXISTS crypto_payment_requests_status_check;

    -- Add the updated constraint
    ALTER TABLE public.crypto_payment_requests
        ADD CONSTRAINT crypto_payment_requests_status_check
        CHECK (status IN ('pending', 'partial', 'activation_pending', 'completed', 'expired', 'activation_failed', 'failed'));
END $$;


-- ── INDEXES ─────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS crypto_pay_req_status_idx
    ON public.crypto_payment_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS crypto_pay_req_account_idx
    ON public.crypto_payment_requests (customer_account_id);
CREATE INDEX IF NOT EXISTS crypto_pay_req_sender_idx
    ON public.crypto_payment_requests (sender_address)
    WHERE sender_address IS NOT NULL;
CREATE INDEX IF NOT EXISTS crypto_pay_req_memo_idx
    ON public.crypto_payment_requests (memo)
    WHERE memo IS NOT NULL;


-- ── AUTO-EXPIRE OLD PENDING REQUESTS ───────────────────────────────
-- Expires pending requests older than 24h. Run via cron or on-demand.
--   UPDATE public.crypto_payment_requests
--   SET status = 'expired', updated_at = now()
--   WHERE status = 'pending' AND expires_at < now();
