-- ─────────────────────────────────────────────────────────────────────
-- EMPIRE AI · MIGRATION 20260615
-- traffic_activity — cycle snapshots from the traffic specialist bot
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS traffic_activity (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cycle       INTEGER NOT NULL DEFAULT 1,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    snapshot    JSONB NOT NULL DEFAULT '{}',
    narrative   TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast recent-cycle lookups
CREATE INDEX IF NOT EXISTS idx_traffic_activity_cycle
    ON traffic_activity (cycle DESC);

-- Index for time-range queries
CREATE INDEX IF NOT EXISTS idx_traffic_activity_ts
    ON traffic_activity (timestamp DESC);

COMMENT ON TABLE traffic_activity IS 'Traffic Specialist bot cycle snapshots — channel status, budget, recommendations, narrative';
COMMENT ON COLUMN traffic_activity.cycle IS 'Cycle number (auto-incrementing)';
COMMENT ON COLUMN traffic_activity.snapshot IS 'Full cycle snapshot: channels, budget_plan, actions, stats';
COMMENT ON COLUMN traffic_activity.narrative IS 'Human-readable traffic report generated by the bot';
