-- Migration: carrier_enrollments
-- Self-service enrollment for insurance carriers to register webhook endpoints.
-- Each enrollment gets a unique API key for authenticating to /api/v1/claim-settled.

CREATE TABLE IF NOT EXISTS public.carrier_enrollments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    carrier_name text NOT NULL,
    contact_name text,
    contact_email text,
    contact_phone text,
    api_key text NOT NULL UNIQUE,
    api_key_label text DEFAULT 'default',
    api_key_active boolean DEFAULT true,
    webhook_url text,
    status text NOT NULL DEFAULT 'active',
    dispatch_ids uuid[] DEFAULT '{}',
    meta jsonb DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    verified_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_carrier_enrollments_api_key ON public.carrier_enrollments(api_key);
CREATE INDEX IF NOT EXISTS idx_carrier_enrollments_status ON public.carrier_enrollments(status);
CREATE INDEX IF NOT EXISTS idx_carrier_enrollments_carrier_name ON public.carrier_enrollments(carrier_name);

COMMENT ON TABLE public.carrier_enrollments IS 'Self-service webhook enrollment for insurance carriers. Each row = one enrolled carrier with a unique API key.';
COMMENT ON COLUMN public.carrier_enrollments.api_key IS 'Unique API key for authenticating to POST /api/v1/claim-settled. Generated by the system on enrollment.';
COMMENT ON COLUMN public.carrier_enrollments.api_key_active IS 'If false, the API key has been revoked and webhook calls will be rejected.';
COMMENT ON COLUMN public.carrier_enrollments.status IS 'active | revoked | suspended';
COMMENT ON COLUMN public.carrier_enrollments.dispatch_ids IS 'Dispatch UUIDs this carrier is linked to (for reporting).';
COMMENT ON COLUMN public.carrier_enrollments.meta IS 'Flexible metadata: integration type, notes, etc.';
COMMENT ON COLUMN public.carrier_enrollments.verified_at IS 'Timestamp of first successful webhook call — confirms the integration works.';
