-- ================================================================
-- EMPIRE V49 · SYNTHETIC INTELLIGENCE TABLES
-- Created: 2026-06-09
-- ================================================================
-- Stores the SI Core's learned parameters across all subsystems.
-- Persisted every 60s so the dashboard always has the latest values.

CREATE TABLE IF NOT EXISTS si_parameters (
  key             text PRIMARY KEY,
  current_value   numeric(10,2) NOT NULL,
  default_value   numeric(10,2) NOT NULL,
  min             numeric(10,2) NOT NULL,
  max             numeric(10,2) NOT NULL,
  samples         int NOT NULL DEFAULT 0,
  confidence      numeric(4,3) NOT NULL DEFAULT 0,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  updated_by      text NOT NULL DEFAULT 'si'
    CHECK (updated_by IN ('si', 'operator', 'agi'))
);

-- Tracks every time a parameter was changed, with the trigger reason.
CREATE TABLE IF NOT EXISTS si_adaptation_log (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  parameter_key   text NOT NULL REFERENCES si_parameters(key),
  old_value       numeric NOT NULL,
  new_value       numeric NOT NULL,
  trigger         text NOT NULL DEFAULT 'outcome'
    CHECK (trigger IN ('outcome', 'meta_cog', 'operator', 'agi')),
  outcome_id      text,  -- FK into the outcome that triggered this change
  meta            jsonb DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS si_adaptation_log_param_idx
  ON si_adaptation_log (parameter_key, created_at DESC);

-- Tracks strategy evolution: each row is a strategy variant.
CREATE TABLE IF NOT EXISTS si_strategies (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL,  -- e.g. "AGGRESSIVE_STRIKE_hail_gen3"
  niche             text NOT NULL DEFAULT '__base__',
  aggressiveness    numeric(4,3) NOT NULL DEFAULT 0.5,
  risk_tolerance    numeric(4,3) NOT NULL DEFAULT 0.5,
  outreach_intensity numeric(4,3) NOT NULL DEFAULT 0.5,
  price_premium     numeric(4,3) NOT NULL DEFAULT 0.5,
  narrow_focus      numeric(4,3) NOT NULL DEFAULT 0.5,
  runs              int NOT NULL DEFAULT 0,
  wins              int NOT NULL DEFAULT 0,
  total_revenue     numeric(12,2) NOT NULL DEFAULT 0,
  current_score     numeric(6,3) NOT NULL DEFAULT 0,
  parent_strategy   text NOT NULL,
  generation        int NOT NULL DEFAULT 0,
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS si_strategies_active_idx
  ON si_strategies (niche, is_active, current_score DESC);

-- Stores the current SI state snapshot (one row, upserted).
CREATE TABLE IF NOT EXISTS si_state (
  id              text PRIMARY KEY DEFAULT 'current',
  snapshot        jsonb NOT NULL,
  feedback_count  int NOT NULL DEFAULT 0,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Stores AGI governor assessment history.
CREATE TABLE IF NOT EXISTS si_agi_assessments (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  cycle           int NOT NULL,
  health          text NOT NULL
    CHECK (health IN ('GREEN', 'YELLOW', 'RED')),
  confidence      numeric(4,3) NOT NULL,
  reasoning       text,
  assessment      jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS si_agi_assessments_cycle_idx
  ON si_agi_assessments (cycle DESC);

-- Stores meta-cognitive insights generated by SI;
CREATE TABLE IF NOT EXISTS si_insights (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  category        text NOT NULL
    CHECK (category IN ('observation', 'calibration', 'calibration_warning',
                        'parameter_shift', 'top_performer', 'strategy_warning',
                        'anomaly', 'recommendation')),
  insight         text NOT NULL,
  data            jsonb DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS si_insights_cat_idx
  ON si_insights (category, created_at DESC);

-- ================================================================
-- SEED INITIAL PARAMETER ROW
-- ================================================================
INSERT INTO si_parameters (key, current_value, default_value, min, max, samples, confidence, updated_by) VALUES
  ('brain.min_urgency', 7, 7, 1, 10, 0, 0, 'si'),
  ('brain.conservatism', 0.3, 0.3, 0.0, 1.0, 0, 0, 'si'),
  ('brain.confidence_threshold', 0.5, 0.5, 0.0, 1.0, 0, 0, 'si'),
  ('buyer.min_acceptance_rate', 0.3, 0.3, 0.0, 1.0, 0, 0, 'si'),
  ('buyer.quality_threshold', 60, 60, 0, 100, 0, 0, 'si'),
  ('buyer.payout_weight', 0.6, 0.6, 0.0, 1.0, 0, 0, 'si'),
  ('buyer.acceptance_weight', 0.4, 0.4, 0.0, 1.0, 0, 0, 'si'),
  ('corridor.base_spend', 15, 15, 0, 200, 0, 0, 'si'),
  ('corridor.panic_reduction', 0.0, 0.0, 0.0, 1.0, 0, 0, 'si'),
  ('matching.metro_weight', 0.40, 0.40, 0.0, 0.6, 0, 0, 'si'),
  ('matching.specialty_weight', 0.25, 0.25, 0.0, 0.4, 0, 0, 'si'),
  ('matching.trust_weight', 0.15, 0.15, 0.0, 0.3, 0, 0, 'si'),
  ('matching.freshness_weight', 0.10, 0.10, 0.0, 0.2, 0, 0, 'si'),
  ('matching.capacity_weight', 0.10, 0.10, 0.0, 0.2, 0, 0, 'si'),
  ('outreach.call_window_start', 8, 8, 6, 12, 0, 0, 'si'),
  ('outreach.call_window_end', 21, 21, 17, 23, 0, 0, 'si'),
  ('outreach.follow_up_delay_h', 48, 48, 12, 168, 0, 0, 'si')
ON CONFLICT (key) DO NOTHING;
